### ISSUE TITLE
Move extras/foreman_callback.py upstream

### ISSUE THREAD

**Issue by agx** [theforeman/foreman_ansible#36]
Hi,
We should move the ansible side of this plugin into upstream ansible? Ansible ships heaps of callback plugins and it would be shipped by default. I'd volunteer to work in it.

**Comment by dLobatog** [comment]
Yeah for sure, I refrained from it in the past since - https://github.com/ansible/ansible/pull/6342 - but I've spoken to ansible peeps recently and they'd include the inventory/callback in core.  In fact the inventory is part of Ansible tower now - http://docs.ansible.com/ansible-tower/latest/html/userguide/inventories.html#red-hat-satellite-6

**Comment by dLobatog** [comment]
Yeah for sure, I refrained from it in the past since - https://github.com/ansible/ansible/pull/6342 - but I've spoken to ansible peeps recently and they'd include the inventory/callback in core.  In fact the inventory is part of Ansible tower now - http://docs.ansible.com/ansible-tower/latest/html/userguide/inventories.html#red-hat-satellite-6

**Comment by agx** [comment]
On Thu, Aug 18, 2016 at 05:13:47AM -0700, Daniel Lobato García wrote:
> Yeah for sure, I refrained from it in the past since - https://github.com/ansible/ansible/pull/6342 - but I've spoken to ansible peeps recently and they'd include the inventory/callback in core.  In fact the inventory is part of Ansible tower now - http://docs.ansible.com/ansible-tower/latest/html/userguide/inventories.html#red-hat-satellite-6

Done in https://github.com/ansible/ansible/pull/17141

**Comment by dLobatog** [comment]
We still keep developing it here or you want to move development there? I'm fine either way, but I'd like to always have it in extras/ in here so people can install it the way the manual says

**Comment by agx** [comment]
On Fri, Aug 19, 2016 at 03:36:01AM -0700, Daniel Lobato García wrote:
> We still keep developing it here or you want to move development
> there? I'm fine either way, but I'd like to always have it in extras/
> in here so people can install it the way the manual says

I'd also keep the copy and would port over changes that make sense
(either way). In order to merge into ansible we need to drop v1 support [1]
among other things which we might want to keep in extras/ for now.

At a later point the version in extras/ can become a verbatim copy of
the one in ansible (iff it gets merged).

[1] https://github.com/ansible/ansible/pull/17141/files/6f2cfacca8c37c290b2d3f785a76ea0e82ba479b#r75362489

**Comment by dLobatog** [comment]
Congrats @agx!
